<?php
return array(
    //info data
    // TEXT KEYWORD => KETERANGAN 
    // MISALKAN ADA KOMENTAR 
    "katakatasapa" => "Hallo Kak",
    "katakatadefault" => "semua etalase kami bahannya sama dan sesuai seperti dilive ya kak",
    "udh" => "siapp kakak, terima kasih ya kak sudah order. Ditunggu untuk barangnya akan kami prosess langsung ya kak",
    "co" => "siapp kakak, terima kasih ya kak sudah order. Ditunggu untuk barangnya akan kami prosess langsung ya kak",
    "campur" => "untuk camur size bisa kakak, tinggal ditulis saja dipesan untuk seller / note ukuran yang kakak mau",
    "mix" => "untuk camur size bisa kakak, tinggal ditulis saja dipesan untuk seller / note ukuran yang kakak mau",
    "beda beda" => "untuk camur size bisa kakak, tinggal ditulis saja dipesan untuk seller / note ukuran yang kakak mau",
    "checkout" => "siapp kakak, terima kasih ya kak sudah order. Ditunggu untuk barangnya akan kami prosess langsung ya kak",
    "sudah" => "siapp kakak, terima kasih ya kak sudah order. Ditunggu untuk barangnya akan kami prosess langsung ya kak",
    "promo" => "promo kami tersedia hanya ketika sesi live saja ya kak, jadi jangan sampai ketinggalan untuk promonya kakak",
    "pengiriman" => "Pengiriman kami dari Jepara ya kak, informasi lebih lanjut tentang pengiriman ada di Etalase, kak. Yuk, dicek!",
    "perkenalkan" => "Maaf kak gak bisa diperlihatkan semua ya kak. karena kita belum ada sample beberapa barang produknya kakak, silakan diorder kakak.",
    "introduce" => "Maaf kak kita ga bisa diperlihatkan semua ya kak. karena kita belum ada sample beberapa barang produknya kakak",
    "eta" => "Maaf kak gak bisa spill semua ya kak. karena kita belum ada sample beberapa barang produknya kakak, silakan diorder kakak.",
    "bahan" => "Semua produk kami berBahan Katun kak (Lembut dan Berkualitas / Elastis), dijamin nyaman ketika digunakan kak. silakan diorder kakak",
    "bhan" => "Semua produk kami berBahan Katun kak (Lembut dan Berkualitas / Elastis), dijamin nyaman ketika digunakan kak. silakan diorder kakak",
    "bhn" => "Semua produk kami berBahan Katun kak (Lembut dan Berkualitas / Elastis), dijamin nyaman ketika digunakan kak. silakan diorder kakak",
    "anak" => "Untuk produk celana chinos anak disetiap pemilihan ukuran tertera pilihan untuk umurnya ya kak.",
    "harga" => "Harga sesuai yang ada di Etalase ya kak, silakan diorder kakak.",
    "rekaman" => "Kita live langsung kak buka rekaman, jika komentar kakak belum dibaca mungkin ketiban ya kak oleh yg lain, jadi ditunggu saja kak.",
    "dibaca" => "Mohon maaf kak jika komentar kakak belum dibaca mungkin chatnya ketiban ya kak oleh yg lain, jadi ditunggu ya kak.",
    "ready" => "Untuk produk selama sesi live untuk stock dijamin tersedia ya kak",
    "diskon2" => "Jangan lewatkan diskon tambahan di livenya, kak. Buruan cek sekarang!",
    "paket" => "Kami juga menyediakan paket hemat, kak. Info lebih lanjut cek di Etalase ya!",
    "garansi" => "Garansi kepuasan pelanggan kami berikan untuk setiap pembelian, kak. Belanja dengan aman!",
    "ongkir" => "Info lebih lanjut tentang tarif pengiriman cek di Etalase, kak. Selamat berbelanja!",
    "update" => "Dapatkan update terbaru produk dan promo di livenya, kak. Jangan sampai ketinggalan!",
    "pertanyaan" => "Ada pertanyaan? Jangan ragu untuk bertanya di livenya, kak. Kami siap membantu!",
    "fitur" => "Cek fitur-fitur menarik produk kami di Etalase, kak. Pasti cocok dengan kebutuhan Anda!",
    "caraorder" => "Belum tahu cara order? Langsung aja cek panduan cara order di livenya, kak. Mudah dan cepat!",
    "testimoni" => "Baca testimoni dari pelanggan kami di Ulasan, kak. Mereka puas, Anda juga akan puas!",
    "tanya" => "Boleh tanya-tanya seputar produk di livenya, kak. Kami siap memberikan informasi!",
    "return" => "Kebetulan ada kebijakan return, kak. Cek di Etalase untuk info lengkapnya!",
    "spill" => "Maaf kak kita gak bisa spill semua ya kak, karena kita belum ada sample beberapa barang produknya kakak",
    "kualitas" => "Produk kami terjamin kualitasnya kakak. Yuk, segera diorder!",
    "stock" => "Semua barang selama sesi live ready stock ya kak, silakan diorder kakak.",
    "diskon" => "untuk vocher diskon / gratis ongkir silahkan diclaim saja ya kak pada keranjang kuningnya",
    "diskom" => "untuk vocher diskon / gratis ongkir silahkan diclaim saja ya kak pada keranjang kuningnya",
    "stok" => "Selama sesi live, semua barang ready stock ya kak. Langsung dicheckout saja kak",
);
